### ISSUE TITLE
builds are slow

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/duojs.org#23]
refreshing the page takes quite awhile.  if we properly used make's dependency handling/phony targets, this wouldn't be the case.

**Comment by dominicbarnes** [comment]
Have you tried comparing the current server against something like [duo-serve](https://github.com/dominicbarnes/duo-serve) (which tries to be more intentional about what/when it builds things than simply running `make` on _every_ incoming request)

**Comment by stephenmathieson** [comment]
Nah, I figured I'd just use what was already here haha

**Comment by dominicbarnes** [comment]
Hehe, I just pushed a branch using duo-serve. It's a lot faster, try it out :)
